### ISSUE TITLE
[Feature Request] Buy delay after audit checks passed

### ISSUE THREAD

**Issue by compunerd4** [JayArrowz/PancakeTokenSniper#10]
It would be nice to have a configurable amount of seconds that will delay the bot in starting the "Buy" after a token passes rugcheck/honeypot check.

ie The bot finds a contract, it passes all the checks, then I want to implement a 10 second delay on purchasing so it doesn't look as much like a bot to the devs

**Comment by JayArrowz** [comment]
Added
