### ISSUE TITLE
[Feature Request] Support for environmental variables

### ISSUE THREAD

**Issue by kosener** [JayArrowz/PancakeTokenSniper#11]
When running in a docker container it would be great if we could override the appsettings configuration options with environmental variables. Configuration could then be specified in a .env file living outside the container.

[Using .env in .NET](https://dusted.codes/dotenv-in-dotnet)

[EnvironmentVariablesExtensions.AddEnvironmentVariables Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.environmentvariablesextensions.addenvironmentvariables?view=dotnet-plat-ext-5.0)

**Comment by JayArrowz** [comment]
You should be able to set the env variable inside the docker container too and you'll be able to override it automatically.


.e.g:

when ASPNETCORE_ENVIRONMENT is set to Development

The following appsettings files will be used for config:
appsettings.json
appsettings.Development.json


The appsettings.Development.json will act as a override for appsettings.json

Feel free to re-open if this did not work for you
