### ISSUE TITLE
[Feature Request] Monitor for liquidity add which can initiate re-audit and buy

### ISSUE THREAD

**Issue by CryptoCarlos21** [JayArrowz/PancakeTokenSniper#12]
**Background**
The bot detects a new token, runs audits and one of those audits is that there isn't enough liquidity which means we can't buy.

If all other audits such as honeypot / rugcheck pass but liquidity fails, it can be a legit token that just hasn't added liquidity yet.

**Request**
Add a liquidity monitor:
 - If the token passes other audit checks but only fails liquidity, monitor it.
 - If it's a specific contract snipe - include liquidity monitoring
 - When liquidity is added, proceed to run the audit again (if it's random contract) or just buy if it's a specific snipe contract
This means we can still come back to a new token after liquidity is added

**Comment by JayArrowz** [comment]
I assume this already happens

i.e. If our min BNB liq amount was 1 BNB

Project A added 0.5 BNB -> BOT GETS ADD LIQUIDITY -> RUG CHECK REJECT
Project A added 0.5 more BNB -> BOT GETS ADD LIQUIDITY -> RUG CHECK PASS

re-open if otherwise
