### ISSUE TITLE
buy specified token

### ISSUE THREAD

**Issue by felewandowski** [JayArrowz/PancakeTokenSniper#23]
hi,  I know which token I wanna buy, could you adjust so you can snipe that specific token?

**Comment by JayArrowz** [comment]
```
If the OnlyBuyWhitelist is enabled the contract will only interact with whitelisted tokens
```

So in the config it'll be something like this:
```
    "OnlyBuyWhitelist": true,
    "WhitelistedTokens": [
      "0x0000000000000000000000000000000000000000",
      "anotherContractAddress"
    ],
```

If OnlyBuyWhitelist is true the bot will only interact with whitelisted contracts hencing buying a specified token.
