### ISSUE TITLE
Need better/newer rug-check for execution reverted: PancakeLibrary: INSUFFICIENT_INPUT_AMOUNT error

### ISSUE THREAD

**Issue by citadella** [JayArrowz/PancakeTokenSniper#3]
It seems new coins might be taking advantage of this or other bots to (presumably) allow initial rug-checks of small amounts but not any more or higher ones once more people are bought in. Not sure what sort of checks can be done, but perhaps waiting until you can read other sell outputs on the contract or perhaps adding a multi-buy/sell feature to follow the coin up so long as it's rising and sell-able?

**Comment by JayArrowz** [comment]
@citadella https://github.com/JayArrowz/PancakeTokenSniper/issues/4 I assume this additional check will help with this

**Comment by citadella** [comment]
Estimates on when it might get added?

**Comment by JayArrowz** [comment]
@citadella tonight or tomorrow

**Comment by citadella** [comment]
Don't have much experience here, but it seems basically ALL the coins I sniped were hit with this scam. They're clearly intended to catch this type of bot-related behavior. I'd be curious what these coins permit. I think your honey pot test buys and then tries to re-sell coins? If so, I might add a tiered purchase option, whereby you buy, say, .00001, sell it, then .0001, then sell, then .001, then sell at which point you can buy the whole snipe amount. It seems these coins don't allow larger sells...

**Comment by JayArrowz** [comment]
I will close this one for now, i think the bot is secure enough with many rug checks in place.
